export type Sku = {
  id: string;
  name: string;
  category: string;
  weightKg: number;
  fragility: "low" | "medium" | "high";
  maxStackKg: number;
  ramp: { fill: string; stroke: string };
};

export type Box = {
  x: number;
  y: number;
  z: number;
  w: number;
  d: number;
  h: number;
  sku: number;
};

export const SKUS: Sku[] = [
  {
    id: "A",
    name: "Tinned tomatoes",
    category: "Tinned & jars",
    weightKg: 9.6,
    fragility: "low",
    maxStackKg: 120,
    ramp: { fill: "#B5D4F4", stroke: "#185FA5" },
  },
  {
    id: "B",
    name: "Pasta & dry goods",
    category: "Dry goods",
    weightKg: 4.2,
    fragility: "low",
    maxStackKg: 60,
    ramp: { fill: "#9FE1CB", stroke: "#0F6E56" },
  },
  {
    id: "C",
    name: "Cereal cartons",
    category: "Cereal",
    weightKg: 2.8,
    fragility: "medium",
    maxStackKg: 18,
    ramp: { fill: "#F5C4B3", stroke: "#993C1D" },
  },
  {
    id: "D",
    name: "Sliced bread",
    category: "Bakery",
    weightKg: 0.6,
    fragility: "high",
    maxStackKg: 2,
    ramp: { fill: "#FAC775", stroke: "#854F0B" },
  },
];

export type EngineStats = {
  status: string;
  objectiveCm: number;
  bestBoundCm: number;
  gapPct: number;
  utilisation: number;
  wallTimeS: number;
  timeLimitS: number;
  workers: number;
  booleans: number;
  branches: number;
  conflicts: number;
  numVars: number;
  numConstraints: number;
  decisionVars: { name: string; formula: string; count: number }[];
  constraintGroups: { name: string; kind: string; count: number }[];
  log: string;
  // Whether the lexicographic stability tie-break ran, and the resulting
  // vertical centre of mass in cm above the deck.
  stabilityApplied: boolean;
  comZcm: number;
};

export type Solution = {
  boxes: Box[];
  heightCm: number;
  utilisation: number;
  status: string;
  engine: EngineStats;
};

// The config the `/constraints` page sends to the engine. Every field is
// optional: an empty body solves the shipped scenario.
export type SolveConfig = {
  stacking?: boolean[][];
  stability?: boolean;
  objectiveWeights?: Record<string, number>;
  rules?: string[];
  solver?: { timeLimitS: number; workers: number };
};

// Seed solution shipped with the app, generated by the CP-SAT engine:
// `uv run -m engine.solve -o src/lib/solution.json`. The store starts from this
// and replaces it once the engine returns a fresh solve. Do not hand-edit.
import solution from "./solution.json";

export const DEFAULT_SOLUTION = solution as unknown as Solution;

// Static seed for the route view, which is not part of the live-solve flow.
export const BOXES: Box[] = DEFAULT_SOLUTION.boxes;

export const PALLET = { w: 100, d: 80, h: 8 };
