export type Sku = {
  id: string;
  name: string;
  category: string;
  weightKg: number;
  fragility: "low" | "medium" | "high";
  maxStackKg: number;
  ramp: { fill: string; stroke: string };
};

export type Box = {
  x: number;
  y: number;
  z: number;
  w: number;
  d: number;
  h: number;
  sku: number;
};

export const SKUS: Sku[] = [
  {
    id: "A",
    name: "Tinned tomatoes",
    category: "Tinned & jars",
    weightKg: 9.6,
    fragility: "low",
    maxStackKg: 120,
    ramp: { fill: "#B5D4F4", stroke: "#185FA5" },
  },
  {
    id: "B",
    name: "Pasta & dry goods",
    category: "Dry goods",
    weightKg: 4.2,
    fragility: "low",
    maxStackKg: 60,
    ramp: { fill: "#9FE1CB", stroke: "#0F6E56" },
  },
  {
    id: "C",
    name: "Cereal cartons",
    category: "Cereal",
    weightKg: 2.8,
    fragility: "medium",
    maxStackKg: 18,
    ramp: { fill: "#F5C4B3", stroke: "#993C1D" },
  },
  {
    id: "D",
    name: "Sliced bread",
    category: "Bakery",
    weightKg: 0.6,
    fragility: "high",
    maxStackKg: 2,
    ramp: { fill: "#FAC775", stroke: "#854F0B" },
  },
];

// Generated by the CP-SAT engine: `uv run -m engine.solve --out src/lib/solution.json`.
// Do not hand-edit; re-run the solver to regenerate.
import solution from "./solution.json";

export const BOXES: Box[] = solution.boxes;

export const SOLUTION = {
  heightCm: solution.heightCm,
  utilisation: solution.utilisation,
  status: solution.status,
};

export const ENGINE = solution.engine;

export const PALLET = { w: 100, d: 80, h: 8 };
